sudo: false
language: php
os:
  - linux
php:
  - 8.0
before_script:
  - composer self-update
  - composer install --no-dev --prefer-dist
script: composer run-script test
notifications:
  email: false
branches:
  only:
  - main
